-- Logistics Operator + Vehicle Driver schema
-- Safe to run multiple times.

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique,
  pickup_latitude double precision,
  pickup_longitude double precision,
  delivery_latitude double precision,
  delivery_longitude double precision,
  pickup_area text,
  packages integer default 1,
  weight numeric(12,2) default 0,
  volume numeric(12,2) default 0,
  distance_km numeric(12,2) default 0,
  load_type text,
  priority text default 'Medium',
  status text default 'available',
  delivery_deadline timestamptz,
  driver_email text,
  completed_at timestamptz,
  pickup_address text,
  drop_address text,
  pickup_lat double precision,
  pickup_lng double precision,
  drop_lat double precision,
  drop_lng double precision,
  commodity text,
  quantity integer,
  earnings numeric(12,2),
  proof_otp text,
  proof_photo_url text,
  proof_notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create or replace function public.set_orders_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.set_orders_updated_at();

create table if not exists public.drivers (
  id uuid primary key default gen_random_uuid(),
  name text,
  driver_name text,
  email text unique,
  phone text,
  contact_no text,
  vehicle_type text,
  vehicle_id text unique,
  status text default 'Idle',
  current_lat double precision,
  current_long double precision,
  last_known_area text,
  sos_active boolean default false,
  last_location_updated_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create or replace function public.set_drivers_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_drivers_updated_at on public.drivers;
create trigger trg_drivers_updated_at
before update on public.drivers
for each row execute function public.set_drivers_updated_at();

create table if not exists public.completed_deliveries (
  id bigint generated by default as identity primary key,
  order_id text unique,
  driver_email text,
  commodity text,
  earnings numeric(12,2),
  completed_at timestamptz default now(),
  created_at timestamptz default now()
);

-- Backward-compatible views for code that references quoted table names.
create or replace view public."Orders" as
select * from public.orders;

create or replace view public."Driver" as
select * from public.drivers;

alter table public.orders enable row level security;
alter table public.drivers enable row level security;
alter table public.completed_deliveries enable row level security;

drop policy if exists orders_select_all on public.orders;
drop policy if exists orders_insert_all on public.orders;
drop policy if exists orders_update_all on public.orders;
create policy orders_select_all on public.orders for select using (true);
create policy orders_insert_all on public.orders for insert with check (true);
create policy orders_update_all on public.orders for update using (true) with check (true);

drop policy if exists drivers_select_all on public.drivers;
drop policy if exists drivers_insert_all on public.drivers;
drop policy if exists drivers_update_all on public.drivers;
create policy drivers_select_all on public.drivers for select using (true);
create policy drivers_insert_all on public.drivers for insert with check (true);
create policy drivers_update_all on public.drivers for update using (true) with check (true);

drop policy if exists completed_select_all on public.completed_deliveries;
drop policy if exists completed_insert_all on public.completed_deliveries;
drop policy if exists completed_update_all on public.completed_deliveries;
create policy completed_select_all on public.completed_deliveries for select using (true);
create policy completed_insert_all on public.completed_deliveries for insert with check (true);
create policy completed_update_all on public.completed_deliveries for update using (true) with check (true);

